### ISSUE TITLE
Mapping of object classes in category_uint8_view.png

### ISSUE THREAD

**Issue by jiunyen-ching** [lsc19940810/SATNet#13]
Hi @ShiceLiu, may I ask what are the categories mapped with colors? For example in this image,
![image](https://user-images.githubusercontent.com/25114361/86769498-d4b27200-c081-11ea-91ed-496952b37071.png)

I want to map their RGB with their classes but I am not sure about other categories like the table/monitor, bookshelf etc.

Thank you in advance!

**Comment by ShiceLiu** [comment]
self.colormap = np.array([[0,0,0.6667],
                                  [0,0,1.0000],
                                  [0,0.3333,1.0000],
                                  [0,0.6667,1.0000],
                                  [0,1.0000,1.0000],
                                  [0.3333,1.0000,0.6667],
                                  [0.6667,1.0000,0.3333],
                                  [1.0000,1.0000,0],
                                  [1.0000,0.6667,0],
                                  [1.0000,0.3333,0],
                                  [1.0000,0,0],
                                  [0.6667,0,0]],dtype=float)


There is a colormap in the 'engine' in the semantic segmentation folder. 12 classes are given in the same order in the paper. and I think it may help you.

**Comment by ShiceLiu** [comment]
> Hi @ShiceLiu, may I ask what are the categories mapped with colors? For example in this image,
> ![image](https://user-images.githubusercontent.com/25114361/86769498-d4b27200-c081-11ea-91ed-496952b37071.png)
> 
> I want to map their RGB with their classes but I am not sure about other categories like the table/monitor, bookshelf etc.
> 
> Thank you in advance!

self.colormap = np.array([[0,0,0.6667],
[0,0,1.0000],
[0,0.3333,1.0000],
[0,0.6667,1.0000],
[0,1.0000,1.0000],
[0.3333,1.0000,0.6667],
[0.6667,1.0000,0.3333],
[1.0000,1.0000,0],
[1.0000,0.6667,0],
[1.0000,0.3333,0],
[1.0000,0,0],
[0.6667,0,0]],dtype=float)

There is a colormap in the 'engine' in the semantic segmentation folder. 12 classes are given in the same order in the paper. and I think it may help you.

**Comment by jiunyen-ching** [comment]
Thank you for your reply! However, I am unable to figure out the 12th class. 

Following the order of the classes and using an RGB color picker, I mapped 11 colors to their classes. 
```
<unknown>  [0,0,0.6667]
ceiling    [0,0,1.0000]
floor      [0,0.3333,1.0000]
wall       [0,0.6667,1.0000]
window     [0,1.0000,1.0000]
chair      [0.3333,1.0000,0.6667]
bed        [0.6667,1.0000,0.3333]
sofa       [1.0000,1.0000,0]
table      [1.0000,0.6667,0]
tv         [1.0000,0.3333,0]
furniture  [1.0000,0,0]
objects    [0.6667,0,0]
```
Example of mapping:
![image](https://user-images.githubusercontent.com/25114361/86903925-95982580-c142-11ea-80fc-808c9e8331f2.png)

One of the images where I found the unknown class' color is being used is 
![image](https://user-images.githubusercontent.com/25114361/86906346-012fc200-c146-11ea-8ad3-8a7690f430ae.png)

I compare the unknown class' color to that of a ceiling side-by-side for confirmation
![image](https://user-images.githubusercontent.com/25114361/86906818-aea2d580-c146-11ea-888e-70040bffb13a.png)
and noticed that the colors are visibly different.

Could you advise further me on this?

**Comment by ShiceLiu** [comment]
<unknown>  [0,0,0.6667]
ceiling    [0,0,1.0000]
floor      [0,0.3333,1.0000]
wall       [0,0.6667,1.0000]
window     [0,1.0000,1.0000]
chair      [0.3333,1.0000,0.6667]
bed        [0.6667,1.0000,0.3333]
sofa       [1.0000,1.0000,0]
table      [1.0000,0.6667,0]
tv         [1.0000,0.3333,0]
furniture  [1.0000,0,0]
objects    [0.6667,0,0]

The class-mapping is right. And the '<unknown>' class represents the objects whose class name you are not necessary to know. Its class index is 0th. We can treat it as a new class label or don't care about it at all.

By the way, when I was doing experiments at that time, I also found some wrong labels or shapes. I thought it might be caused by rendering. These mistakes would lead to inaccurate results, but these noises would, to some extent, make the model robust. So I don't think it is a big problem.

**Comment by jiunyen-ching** [comment]
I see. That's interesting to know. Thanks a lot for your feedback!
