### ISSUE TITLE
Can not find 'category_uint8.png' of suncg when test the trained segmentation model

### ISSUE THREAD

**Issue by LongruiDong** [lsc19940810/SATNet#3]
HI,
I have downloaded  [pretrained model](https://github.com/ShiceLiu/SATNet#pretrained-models) and [datasets](https://github.com/ShiceLiu/SATNet#Datasets) from BaiDuYun.
I want to evaluate the pretrained model to test segmentation on suncg_depth. In SATNet/Semantic_Segmentation/**seg_depth_suncg.py** at about line 167:
```
        if train == True:
            HHA_path = '/media/jason/JetsonSSD/myselect_suncg_HHA'
        else:
            HHA_path = '~/SATNet/SATNet_dadasets/myselect_suncg_val_HHA' #me: for test

        fid = open(path, "r") # me: image_list_val.txt
        self.colorlist = []
        self.categlist = []
        ind = 1 # HHA's index begins with 1, instead of 0.
        for line in fid.readlines():
            line = line.rstrip("\n")
            line1 = line[0:len(line)-9] + 'category_uint8.png'
            if os.path.exists(line) and os.path.exists(line1):
                self.colorlist.append(HHA_path+'/%06d.png'%ind)
                self.categlist.append(line1)
```
 in above code, '**path**' refer to  '~/SATNet/SATNet_dadasets/image_list_val.txt', in this txt I got:
```
/home/jason/lsc_datasets/07346cd7b3ea32d8e0828175dd35d657/images/000031_color.jpg
/home/jason/lsc_datasets/07346cd7b3ea32d8e0828175dd35d657/images/000019_color.jpg
/home/jason/lsc_datasets/07346cd7b3ea32d8e0828175dd35d657/images/000009_color.jpg
......
```
'**if os.path.exists(line) and os.path.exists(line1):**' As far as I understand it，this line apparently need to find **xxxxxx_color.jpg** and **xxxxxx_category_uint8.png** in relevant suncg testset somewhere.But from dataset downloaded from BaiDuYun, I can not find these files, Did I miss something? 
Could you give me some help? Thanks~~

**Comment by ShiceLiu** [comment]
@LongruiDong 
It is my fault. Because of too mach data used here, I forgot to pack images in the SUNCG-RGBD. 
I am going to upload this part as soon as possible and tell you how to acquire it in the README.

**Comment by ShiceLiu** [comment]
@LongruiDong 
I have uploaded SUNCGRGBD_images and you can follow the README to use it.
