### ISSUE TITLE
Unable to download pretrained models from Baidu Pan

### ISSUE THREAD

**Issue by krrish94** [lsc19940810/SATNet#4]
Hi,

I am trying to experiment with a few SATNet models for scene completion. However, I cannot seem to download from Baidu Pan (I'm in Canads, so don't have an account). Is there an alternate way in which I could get access to the models?

Thanks!

**Comment by ShiceLiu** [comment]
@krrish94 

Hi,

I am sorry for this problem. As you know, we can't access Google in China. Would you mind telling me your email and what you need? If the models are not so big, I could send you by email.

Yours,
Shice Liu

**Comment by krrish94** [comment]
I'm looking to benchmark wrt the SUNCG_D, SUNCG_RGBD semantic segmentation as well as the semantic scene completion models. My email is krrish94 [at] gmail [dot] com
