### ISSUE TITLE
How to generate '.npz' file from the raw '.bin' ground truth?

### ISSUE THREAD

**Issue by charlesCXK** [lsc19940810/SATNet#7]
Hi,
thanks for your great work and share.
Sorry to bother you. I have been looking for the GroundTruth of NYU and NYUCAD for a long time. SSCNet supplies the GroundTruth in the format of .bin, but I am not familiar with caffee and cuda, so I have difficulty understanding how he used these '.bin' files. And I find NYU's in your Baiduyun link. Do you mind sharing the code that generates data in '.npz' format from the '.bin' file? Thank you very much!

**Comment by ShiceLiu** [comment]
@charlesCXK 

We have uploaded the 'util' directory for data preprocessing and I think it will help you. But so sorry that you should modify some parts in the code.

**Comment by charlesCXK** [comment]
I'm so surprised to get a reply so quickly. Thank you very much !
